# Generated by Django 4.2.2 on 2023-07-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_loginform_delete_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loginform',
            new_name='userdata',
        ),
    ]
